amqp:
  admin:
    auto-create: false
  queues:
    video-created:
      exchange: video.events
      routing-key: video.created
      queue: video.created.queue
    video-encoded:
      exchange: video.events
      routing-key: video.encoded
      queue: video.encoded.queue

google:
  cloud:
    credentials: ${GOOGLE_CLOUD_CREDENTIALS}
    project-id: ${GOOGLE_CLOUD_PROJECT_ID}
    storage:
      catalogo-videos:
        bucket: catalogo_videos_tcc
        connectTimeout: 1000
        readTimeout: 2000
        retryDelay: 50
        retry-max-attempts: 2
        retry-max-delay: 50
        retry-multiplier: 1.0

logging:
  level:
    ROOT: INFO
    org.jonasribeiro.admin.catalogo: DEBUG

server:
    port: 8080
    servlet:
      context-path: /api
    compression:
        enabled: true # Enable compression for responses
        mime-types: application/json,application/xml,text/html,text/plain,text/css,text/javascript,application/javascript,application/x-javascript,application/x-www-form-urlencoded
    undertow:
      threads:
        io: 4 # Number of IO threads
        worker: 64 # Number of worker threads

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&ServerTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false # Enable auto-commit for transactions
      maximum-pool-size: 20 # Maximum number of connections in the pool
      minimum-idle: 10 # Minimum number of idle connections in the pool
      connection-timeout: 250 # Connection timeout in milliseconds (30 seconds)
      max-lifetime: 600000 # Maximum lifetime of a connection in milliseconds (30 minutes)
      pool-name: master # Name of the connection pool
  jpa:
      open-in-view: false # Disable Open EntityManager in View
      show-sql: true # Show SQL statements in logs
      hibernate:
        ddl-auto: none # Disable automatic schema generation
      properties:
         "[hibernate.dialect]": org.hibernate.dialect.MySQL8Dialect # Use MySQL 8 dialect
         "[hibernate.generate_statistics]": false # Enable Hibernate statistics
         "[hibernate.connection.provider_disables_autocommit]": true # Use C3P0 connection provider
  rabbitmq:
    dynamic: ${amqp.admin.auto-create}
    host: ${amqp.host}
    port: ${amqp.port}
    username: ${amqp.username}
    password: ${amqp.password}
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 100GB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}

storage:
  catalogo-videos:
    filename-pattern: type-{type}
    location-pattern: videoId-{videoId}




